language: node_js
node_js:
  - node
cache:
  directories:
    - "node_modules"
install:
  - yarn
  - yarn upgrade
script:
  - yarn build
  - test -f $WEB_INDEX -a -s $WEB_INDEX
deploy:
  email: taichunmin@gmail.com
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  local_dir: .vuepress/dist
  name: taichunmin
  provider: pages
  skip-cleanup: true
  on:
    branch: master